# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pRTzxig_7wzMeQLwnjgmB8thLEoiFMcn
"""

#Simple Interest(Choosing Mnemonic variable names-principle,time_period,rate)

principal=float(input("enter the principal value"))
time_period=float(input("enter the timeperiod"))
rate=float(input("enter the rate"))
interest=(principal*time_period*rate)/100
print(interest)

